In [ ]:
import numpy as np

print("Evaluación de la matriz A:")
A = np.array([[2,1],[3,4]])

print("La matriz", A)


B = 1 + max(np.abs(np.poly(A)/np.poly(A)[0])) #calculo de la cota de cauchy-lagrage para polinomios

def evaluar(pol, x): #definiion de la funciòn evaluar para polinomios
  pol = pol.copy()
  n = len(pol) - 1
  return sum([pol[i] * x ** (n-i) for i in range(n+1)])

#criterio de strums#
P = []#sucesión de polinomios
n = A.shape[0]#dimensiòn de la matriz por tanto numero de iteraciones de la sucesión
polinomio_original = np.poly(A)#determinante de (A-I\landa)
polinomio_polarizado = np.asarray([polinomio_original[i] * B ** (n - i) for i in range(n + 1)]) #cambio de variable#
P.append(polinomio_polarizado)#P_0 primer tèrmino de la sucesión
P.append(np.array([P[0][i] * (n-i) for i in range(0, n)]))#P_1 segundo término de la sucesión

for i in range(2, n + 1):
  P.append(-np.polynomial.polynomial.polydiv(P[i-2], P[i-1])[1])#descripción
def conteo_raices(intervalo):
  (a, b) = intervalo
  conteo_a = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion en la lista dada por el teorema de strums evaluada en los limites inferiores de cada subintervalo dada por la particiones
  for i in range(1, n+1):
    if evaluar(P[i-1], a) * evaluar(P[i],a) < 0:
      conteo_a += 1

  conteo_b = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion
  for i in range(1,n+1):
    if evaluar(P[i-1], b)*evaluar(P[i],b) < 0:
      conteo_b += 1

  return conteo_a - conteo_b #numero de raices en los intervalos encontrados en la partición#
max_raices = conteo_raices((-1, 1))
n1 = 0
while max_raices > 1:
  k = 2 ** n1
  intervalos = [(-1 + j / k, - 1 + (j + 1) / k) for j in range(2 * k)] #particion del intervalo [-1,1]#

  max_raices = 0
  for intervalo in intervalos:

    N = conteo_raices(intervalo) #conteo de raices en cada subintervalo definido por la partción

    if N > max_raices:
      max_raices = N #localización de la raices en las particiones del intervalo[-1,1]
  n1 += 1

 #aislamiento de raices#
verdaderos_intervalos = []
for intervalo in intervalos:
  if conteo_raices(intervalo) > 0:
    verdaderos_intervalos.append(intervalo)

def biseccion(intervalo, tol): #Función, extremos, y tolerancia
  (a, b) = intervalo
  p = a + ( b - a ) / 2 #Punto medio del intervalo
  if evaluar(P[0], p) == 0 or b-a < tol:
    return p
  elif evaluar(P[0], a) * evaluar(P[0], p) <0:
    return biseccion((a, p),tol)
  elif evaluar(P[0], p) * evaluar(P[0], b) <0:
    return biseccion((p, b),tol)  

#encontrar las raices del polinomio parametrizado usando el método de bisección#
raices = []
for intervalo in verdaderos_intervalos:
  raices.append(biseccion(intervalo, 10**(-10)))

valores_propios = [B * raiz for raiz in raices]#reparametrización de las raíces ubicadas en [-B,B]

#calculo de los vectores propios por gradiente conjugado#
import numpy as np

def gradiente_conjugado(A, b, x0=None, tol=1e-10, max_iter=1000):

    n = len(b)
    x = np.zeros_like(b) if x0 is None else x0.copy()  # Vector inicial (usualmente 0)
    r = b - np.dot(A, x)  # Resíduo inicial
    p = r.copy()  # Dirección de búsqueda inicial

    for k in range(max_iter):
        # Producto escalar de p con r using .flatten() to ensure 1D arrays for dot product
        # This ensures the dot product calculates a scalar as intended.
        alpha = np.dot(r.flatten(), r.flatten()) / np.dot(p.flatten(), np.dot(A, p).flatten())

        # Actualización de la solución
        x = x + alpha * p

        # Nuevo residuo
        r_new = r - alpha * np.dot(A, p)

        # Comprobar la convergencia
        if np.linalg.norm(r_new) < tol:
            print(f"Convergió después de {k+1} iteraciones.")
            return x

        # Calculamos beta using .flatten() to ensure 1D arrays for dot product
        beta = np.dot(r_new.flatten(), r_new.flatten()) / np.dot(r.flatten(), r.flatten())

        # Actualizamos la dirección
        p = r_new + beta * p

        r = r_new  # Actualizamos el residuo

    print("Alcanzado el número máximo de iteraciones.")
    return x
#solucion del sistema de ecuaciones para cada valor propio
for valor in valores_propios:
  #sistema de ecuaciones para cada valor propio
  A_hat = A - valor * np.eye(n) #matriz (A-\landa I)
  b = np.zeros((n,1)) #vector 0 de dimension nx1
  x0 = np.ones((n,1))#valor de inicio para el método gauss seidel en este caso la identidad
  x = gradiente_conjugado(A_hat,b,x0, 1e-4,100)#solución del sistema de ecuaciones (A-\landa I)x=0
  print(f"El autovector asociado a {valor} es {x}")


Evaluación de la matriz A
La matriz [[2 1]
 [3 4]]
Convergió después de 1 iteraciones.
El autovector asociado a 1.0000000000873115 es [[ 0.5]
 [-0.5]]
Convergió después de 1 iteraciones.
El autovector asociado a 5.000000000029104 es [[0.5]
 [1.5]]


In [8]:
import numpy as np

print("Evaluación de la matriz B:")
A = np.array([[3,2],[3,4]])

print("La matriz", A)


B = 1 + max(np.abs(np.poly(A)/np.poly(A)[0])) #calculo de la cota de cauchy-lagrage para polinomios

def evaluar(pol, x): #definiion de la funciòn evaluar para polinomios
  pol = pol.copy()
  n = len(pol) - 1
  return sum([pol[i] * x ** (n-i) for i in range(n+1)])

#criterio de strums#
P = []#sucesión de polinomios
n = A.shape[0]#dimensiòn de la matriz por tanto numero de iteraciones de la sucesión
polinomio_original = np.poly(A)#determinante de (A-I\landa)
polinomio_polarizado = np.asarray([polinomio_original[i] * B ** (n - i) for i in range(n + 1)]) #cambio de variable#
P.append(polinomio_polarizado)#P_0 primer tèrmino de la sucesión
P.append(np.array([P[0][i] * (n-i) for i in range(0, n)]))#P_1 segundo término de la sucesión

for i in range(2, n + 1):
  P.append(-np.polynomial.polynomial.polydiv(P[i-2], P[i-1])[1])#descripción
def conteo_raices(intervalo):
  (a, b) = intervalo
  conteo_a = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion en la lista dada por el teorema de strums evaluada en los limites inferiores de cada subintervalo dada por la particiones
  for i in range(1, n+1):
    if evaluar(P[i-1], a) * evaluar(P[i],a) < 0:
      conteo_a += 1

  conteo_b = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion
  for i in range(1,n+1):
    if evaluar(P[i-1], b)*evaluar(P[i],b) < 0:
      conteo_b += 1

  return conteo_a - conteo_b #numero de raices en los intervalos encontrados en la partición#
max_raices = conteo_raices((-1, 1))
n1 = 0
while max_raices > 1:
  k = 2 ** n1
  intervalos = [(-1 + j / k, - 1 + (j + 1) / k) for j in range(2 * k)] #particion del intervalo [-1,1]#

  max_raices = 0
  for intervalo in intervalos:

    N = conteo_raices(intervalo) #conteo de raices en cada subintervalo definido por la partción

    if N > max_raices:
      max_raices = N #localización de la raices en las particiones del intervalo[-1,1]
  n1 += 1

 #aislamiento de raices#
verdaderos_intervalos = []
for intervalo in intervalos:
  if conteo_raices(intervalo) > 0:
    verdaderos_intervalos.append(intervalo)

def biseccion(intervalo, tol): #Función, extremos, y tolerancia
  (a, b) = intervalo
  p = a + ( b - a ) / 2 #Punto medio del intervalo
  if evaluar(P[0], p) == 0 or b-a < tol:
    return p
  elif evaluar(P[0], a) * evaluar(P[0], p) <0:
    return biseccion((a, p),tol)
  elif evaluar(P[0], p) * evaluar(P[0], b) <0:
    return biseccion((p, b),tol)  

#encontrar las raices del polinomio parametrizado usando el método de bisección#
raices = []
for intervalo in verdaderos_intervalos:
  raices.append(biseccion(intervalo, 10**(-10)))

valores_propios = [B * raiz for raiz in raices]#reparametrización de las raíces ubicadas en [-B,B]

#calculo de los vectores propios por gradiente conjugado#
import numpy as np

def gradiente_conjugado(A, b, x0=None, tol=1e-10, max_iter=1000):

    n = len(b)
    x = np.zeros_like(b) if x0 is None else x0.copy()  # Vector inicial (usualmente 0)
    r = b - np.dot(A, x)  # Resíduo inicial
    p = r.copy()  # Dirección de búsqueda inicial

    for k in range(max_iter):
        # Producto escalar de p con r using .flatten() to ensure 1D arrays for dot product
        # This ensures the dot product calculates a scalar as intended.
        alpha = np.dot(r.flatten(), r.flatten()) / np.dot(p.flatten(), np.dot(A, p).flatten())

        # Actualización de la solución
        x = x + alpha * p

        # Nuevo residuo
        r_new = r - alpha * np.dot(A, p)

        # Comprobar la convergencia
        if np.linalg.norm(r_new) < tol:
            print(f"Convergió después de {k+1} iteraciones.")
            return x

        # Calculamos beta using .flatten() to ensure 1D arrays for dot product
        beta = np.dot(r_new.flatten(), r_new.flatten()) / np.dot(r.flatten(), r.flatten())

        # Actualizamos la dirección
        p = r_new + beta * p

        r = r_new  # Actualizamos el residuo

    print("Alcanzado el número máximo de iteraciones.")
    return x
#solucion del sistema de ecuaciones para cada valor propio
for valor in valores_propios:
  #sistema de ecuaciones para cada valor propio
  A_hat = A - valor * np.eye(n) #matriz (A-\landa I)
  b = np.zeros((n,1)) #vector 0 de dimension nx1
  x0 = np.ones((n,1))#valor de inicio para el método gauss seidel en este caso la identidad
  x = gradiente_conjugado(A_hat,b,x0, 1e-4,100)#solución del sistema de ecuaciones (A-\landa I)x=0
  print(f"El autovector asociado a {valor} es {x}")

Evaluación de la matriz B:
La matriz [[3 2]
 [3 4]]
Convergió después de 1 iteraciones.
El autovector asociado a 1.0 es [[ 0.2]
 [-0.2]]
Convergió después de 1 iteraciones.
El autovector asociado a 6.0 es [[0.8]
 [1.2]]


In [10]:
import numpy as np

print("Evaluación de la matriz C:")
A = np.array([[2,3],[1,4]])

print("La matriz", A)


B = 1 + max(np.abs(np.poly(A)/np.poly(A)[0])) #calculo de la cota de cauchy-lagrage para polinomios

def evaluar(pol, x): #definiion de la funciòn evaluar para polinomios
  pol = pol.copy()
  n = len(pol) - 1
  return sum([pol[i] * x ** (n-i) for i in range(n+1)])

#criterio de strums#
P = []#sucesión de polinomios
n = A.shape[0]#dimensiòn de la matriz por tanto numero de iteraciones de la sucesión
polinomio_original = np.poly(A)#determinante de (A-I\landa)
polinomio_polarizado = np.asarray([polinomio_original[i] * B ** (n - i) for i in range(n + 1)]) #cambio de variable#
P.append(polinomio_polarizado)#P_0 primer tèrmino de la sucesión
P.append(np.array([P[0][i] * (n-i) for i in range(0, n)]))#P_1 segundo término de la sucesión

for i in range(2, n + 1):
  P.append(-np.polynomial.polynomial.polydiv(P[i-2], P[i-1])[1])#descripción
def conteo_raices(intervalo):
  (a, b) = intervalo
  conteo_a = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion en la lista dada por el teorema de strums evaluada en los limites inferiores de cada subintervalo dada por la particiones
  for i in range(1, n+1):
    if evaluar(P[i-1], a) * evaluar(P[i],a) < 0:
      conteo_a += 1

  conteo_b = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion
  for i in range(1,n+1):
    if evaluar(P[i-1], b)*evaluar(P[i],b) < 0:
      conteo_b += 1

  return conteo_a - conteo_b #numero de raices en los intervalos encontrados en la partición#
max_raices = conteo_raices((-1, 1))
n1 = 0
while max_raices > 1:
  k = 2 ** n1
  intervalos = [(-1 + j / k, - 1 + (j + 1) / k) for j in range(2 * k)] #particion del intervalo [-1,1]#

  max_raices = 0
  for intervalo in intervalos:

    N = conteo_raices(intervalo) #conteo de raices en cada subintervalo definido por la partción

    if N > max_raices:
      max_raices = N #localización de la raices en las particiones del intervalo[-1,1]
  n1 += 1

 #aislamiento de raices#
verdaderos_intervalos = []
for intervalo in intervalos:
  if conteo_raices(intervalo) > 0:
    verdaderos_intervalos.append(intervalo)

def biseccion(intervalo, tol): #Función, extremos, y tolerancia
  (a, b) = intervalo
  p = a + ( b - a ) / 2 #Punto medio del intervalo
  if evaluar(P[0], p) == 0 or b-a < tol:
    return p
  elif evaluar(P[0], a) * evaluar(P[0], p) <0:
    return biseccion((a, p),tol)
  elif evaluar(P[0], p) * evaluar(P[0], b) <0:
    return biseccion((p, b),tol)  

#encontrar las raices del polinomio parametrizado usando el método de bisección#
raices = []
for intervalo in verdaderos_intervalos:
  raices.append(biseccion(intervalo, 10**(-10)))

valores_propios = [B * raiz for raiz in raices]#reparametrización de las raíces ubicadas en [-B,B]

#calculo de los vectores propios por gradiente conjugado#
import numpy as np

def gradiente_conjugado(A, b, x0=None, tol=1e-10, max_iter=1000):

    n = len(b)
    x = np.zeros_like(b) if x0 is None else x0.copy()  # Vector inicial (usualmente 0)
    r = b - np.dot(A, x)  # Resíduo inicial
    p = r.copy()  # Dirección de búsqueda inicial

    for k in range(max_iter):
        # Producto escalar de p con r using .flatten() to ensure 1D arrays for dot product
        # This ensures the dot product calculates a scalar as intended.
        alpha = np.dot(r.flatten(), r.flatten()) / np.dot(p.flatten(), np.dot(A, p).flatten())

        # Actualización de la solución
        x = x + alpha * p

        # Nuevo residuo
        r_new = r - alpha * np.dot(A, p)

        # Comprobar la convergencia
        if np.linalg.norm(r_new) < tol:
            print(f"Convergió después de {k+1} iteraciones.")
            return x

        # Calculamos beta using .flatten() to ensure 1D arrays for dot product
        beta = np.dot(r_new.flatten(), r_new.flatten()) / np.dot(r.flatten(), r.flatten())

        # Actualizamos la dirección
        p = r_new + beta * p

        r = r_new  # Actualizamos el residuo

    print("Alcanzado el número máximo de iteraciones.")
    return x
#solucion del sistema de ecuaciones para cada valor propio
for valor in valores_propios:
  #sistema de ecuaciones para cada valor propio
  A_hat = A - valor * np.eye(n) #matriz (A-\landa I)
  b = np.zeros((n,1)) #vector 0 de dimension nx1
  x0 = np.ones((n,1))#valor de inicio para el método gauss seidel en este caso la identidad
  x = gradiente_conjugado(A_hat,b,x0, 1e-4,100)#solución del sistema de ecuaciones (A-\landa I)x=0
  print(f"El autovector asociado a {valor} es {x}")

Evaluación de la matriz C:
La matriz [[2 3]
 [1 4]]
Convergió después de 1 iteraciones.
El autovector asociado a 1.0000000000873115 es [[0.]
 [0.]]
Convergió después de 1 iteraciones.
El autovector asociado a 5.000000000029104 es [[0.]
 [0.]]


Para esta matriz "C" el algoritmo converge correctamente, solo que en el calculo de los vectores propios asociados a cada auto valor el método del gradiente conjugado llega a una solución muy cercana a cero, por tanto lo redondea a cero. Es como si el auto vector asociado a 1 fuera $\delta_1$(1,1) y el auto vector asociado a 5 fuera $\delta_2$(-3,1) donde $\delta_1$ y $\delta_2$ son números muy cercanos a cero, por tanto los redondea a 0 

In [ ]:
import numpy as np

print("Evaluación de la matriz D:")
A = np.array([[1,1,2],[2,1,1],[1,1,3]])

print("La matriz", A)


B = 1 + max(np.abs(np.poly(A)/np.poly(A)[0])) #calculo de la cota de cauchy-lagrage para polinomios

def evaluar(pol, x): #definiion de la funciòn evaluar para polinomios
  pol = pol.copy()
  n = len(pol) - 1
  return sum([pol[i] * x ** (n-i) for i in range(n+1)])

#criterio de strums#
P = []#sucesión de polinomios
n = A.shape[0]#dimensiòn de la matriz por tanto numero de iteraciones de la sucesión
polinomio_original = np.poly(A)#determinante de (A-I\landa)
polinomio_polarizado = np.asarray([polinomio_original[i] * B ** (n - i) for i in range(n + 1)]) #cambio de variable#
P.append(polinomio_polarizado)#P_0 primer tèrmino de la sucesión
P.append(np.array([P[0][i] * (n-i) for i in range(0, n)]))#P_1 segundo término de la sucesión

for i in range(2, n + 1):
  P.append(-np.polynomial.polynomial.polydiv(P[i-2], P[i-1])[1])#descripción
def conteo_raices(intervalo):
  (a, b) = intervalo
  conteo_a = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion en la lista dada por el teorema de strums evaluada en los limites inferiores de cada subintervalo dada por la particiones
  for i in range(1, n+1):
    if evaluar(P[i-1], a) * evaluar(P[i],a) < 0:
      conteo_a += 1

  conteo_b = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion
  for i in range(1,n+1):
    if evaluar(P[i-1], b)*evaluar(P[i],b) < 0:
      conteo_b += 1

  return conteo_a - conteo_b #numero de raices en los intervalos encontrados en la partición#
max_raices = conteo_raices((-1, 1))
n1 = 0
while max_raices > 1:
  k = 2 ** n1
  intervalos = [(-1 + j / k, - 1 + (j + 1) / k) for j in range(2 * k)] #particion del intervalo [-1,1]#

  max_raices = 0
  for intervalo in intervalos:

    N = conteo_raices(intervalo) #conteo de raices en cada subintervalo definido por la partción

    if N > max_raices:
      max_raices = N #localización de la raices en las particiones del intervalo[-1,1]
  n1 += 1

 #aislamiento de raices#
verdaderos_intervalos = []
for intervalo in intervalos:
  if conteo_raices(intervalo) > 0:
    verdaderos_intervalos.append(intervalo)

def biseccion(intervalo, tol): #Función, extremos, y tolerancia
  (a, b) = intervalo
  p = a + ( b - a ) / 2 #Punto medio del intervalo
  if evaluar(P[0], p) == 0 or b-a < tol:
    return p
  elif evaluar(P[0], a) * evaluar(P[0], p) <0:
    return biseccion((a, p),tol)
  elif evaluar(P[0], p) * evaluar(P[0], b) <0:
    return biseccion((p, b),tol)  

#encontrar las raices del polinomio parametrizado usando el método de bisección#
raices = []
for intervalo in verdaderos_intervalos:
  raices.append(biseccion(intervalo, 10**(-10)))

valores_propios = [B * raiz for raiz in raices]#reparametrización de las raíces ubicadas en [-B,B]

#calculo de los vectores propios por gradiente conjugado#
import numpy as np

def gradiente_conjugado(A, b, x0=None, tol=1e-10, max_iter=1000):

    n = len(b)
    x = np.zeros_like(b) if x0 is None else x0.copy()  # Vector inicial (usualmente 0)
    r = b - np.dot(A, x)  # Resíduo inicial
    p = r.copy()  # Dirección de búsqueda inicial

    for k in range(max_iter):
        # Producto escalar de p con r using .flatten() to ensure 1D arrays for dot product
        # This ensures the dot product calculates a scalar as intended.
        alpha = np.dot(r.flatten(), r.flatten()) / np.dot(p.flatten(), np.dot(A, p).flatten())

        # Actualización de la solución
        x = x + alpha * p

        # Nuevo residuo
        r_new = r - alpha * np.dot(A, p)

        # Comprobar la convergencia
        if np.linalg.norm(r_new) < tol:
            print(f"Convergió después de {k+1} iteraciones.")
            return x

        # Calculamos beta using .flatten() to ensure 1D arrays for dot product
        beta = np.dot(r_new.flatten(), r_new.flatten()) / np.dot(r.flatten(), r.flatten())

        # Actualizamos la dirección
        p = r_new + beta * p

        r = r_new  # Actualizamos el residuo

    print("Alcanzado el número máximo de iteraciones.")
    return x
#solucion del sistema de ecuaciones para cada valor propio
for valor in valores_propios:
  #sistema de ecuaciones para cada valor propio
  A_hat = A - valor * np.eye(n) #matriz (A-\landa I)
  b = np.zeros((n,1)) #vector 0 de dimension nx1
  x0 = np.ones((n,1))#valor de inicio para el método gauss seidel en este caso la identidad
  x = gradiente_conjugado(A_hat,b,x0, 1e-4,100)#solución del sistema de ecuaciones (A-\landa I)x=0
  print(f"El autovector asociado a {valor} es {x}")

Evaluación de la matriz D:
La matriz [[1 1 2]
 [2 1 1]
 [1 1 3]]
Alcanzado el número máximo de iteraciones.
El autovector asociado a -0.2851424819673411 es [[ 0.07154441]
 [-0.13399349]
 [ 0.02309086]]
Convergió después de 10 iteraciones.
El autovector asociado a 0.778123837604653 es [[ 0.04354379]
 [ 0.2957823 ]
 [-0.15270639]]
Alcanzado el número máximo de iteraciones.
El autovector asociado a 4.507018644071649 es [[0.88434436]
 [0.82929848]
 [1.1365422 ]]


In [12]:
import numpy as np

print("Evaluación de la matriz E:")
A = np.array([[1,1,2],[2,1,3],[1,1,1]])

print("La matriz", A)


B = 1 + max(np.abs(np.poly(A)/np.poly(A)[0])) #calculo de la cota de cauchy-lagrage para polinomios

def evaluar(pol, x): #definiion de la funciòn evaluar para polinomios
  pol = pol.copy()
  n = len(pol) - 1
  return sum([pol[i] * x ** (n-i) for i in range(n+1)])

#criterio de strums#
P = []#sucesión de polinomios
n = A.shape[0]#dimensiòn de la matriz por tanto numero de iteraciones de la sucesión
polinomio_original = np.poly(A)#determinante de (A-I\landa)
polinomio_polarizado = np.asarray([polinomio_original[i] * B ** (n - i) for i in range(n + 1)]) #cambio de variable#
P.append(polinomio_polarizado)#P_0 primer tèrmino de la sucesión
P.append(np.array([P[0][i] * (n-i) for i in range(0, n)]))#P_1 segundo término de la sucesión

for i in range(2, n + 1):
  P.append(-np.polynomial.polynomial.polydiv(P[i-2], P[i-1])[1])#descripción
def conteo_raices(intervalo):
  (a, b) = intervalo
  conteo_a = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion en la lista dada por el teorema de strums evaluada en los limites inferiores de cada subintervalo dada por la particiones
  for i in range(1, n+1):
    if evaluar(P[i-1], a) * evaluar(P[i],a) < 0:
      conteo_a += 1

  conteo_b = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion
  for i in range(1,n+1):
    if evaluar(P[i-1], b)*evaluar(P[i],b) < 0:
      conteo_b += 1

  return conteo_a - conteo_b #numero de raices en los intervalos encontrados en la partición#
max_raices = conteo_raices((-1, 1))
n1 = 0
while max_raices > 1:
  k = 2 ** n1
  intervalos = [(-1 + j / k, - 1 + (j + 1) / k) for j in range(2 * k)] #particion del intervalo [-1,1]#

  max_raices = 0
  for intervalo in intervalos:

    N = conteo_raices(intervalo) #conteo de raices en cada subintervalo definido por la partción

    if N > max_raices:
      max_raices = N #localización de la raices en las particiones del intervalo[-1,1]
  n1 += 1

 #aislamiento de raices#
verdaderos_intervalos = []
for intervalo in intervalos:
  if conteo_raices(intervalo) > 0:
    verdaderos_intervalos.append(intervalo)

def biseccion(intervalo, tol): #Función, extremos, y tolerancia
  (a, b) = intervalo
  p = a + ( b - a ) / 2 #Punto medio del intervalo
  if evaluar(P[0], p) == 0 or b-a < tol:
    return p
  elif evaluar(P[0], a) * evaluar(P[0], p) <0:
    return biseccion((a, p),tol)
  elif evaluar(P[0], p) * evaluar(P[0], b) <0:
    return biseccion((p, b),tol)  

#encontrar las raices del polinomio parametrizado usando el método de bisección#
raices = []
for intervalo in verdaderos_intervalos:
  raices.append(biseccion(intervalo, 10**(-10)))

valores_propios = [B * raiz for raiz in raices]#reparametrización de las raíces ubicadas en [-B,B]

#calculo de los vectores propios por gradiente conjugado#
import numpy as np

def gradiente_conjugado(A, b, x0=None, tol=1e-10, max_iter=1000):

    n = len(b)
    x = np.zeros_like(b) if x0 is None else x0.copy()  # Vector inicial (usualmente 0)
    r = b - np.dot(A, x)  # Resíduo inicial
    p = r.copy()  # Dirección de búsqueda inicial

    for k in range(max_iter):
        # Producto escalar de p con r using .flatten() to ensure 1D arrays for dot product
        # This ensures the dot product calculates a scalar as intended.
        alpha = np.dot(r.flatten(), r.flatten()) / np.dot(p.flatten(), np.dot(A, p).flatten())

        # Actualización de la solución
        x = x + alpha * p

        # Nuevo residuo
        r_new = r - alpha * np.dot(A, p)

        # Comprobar la convergencia
        if np.linalg.norm(r_new) < tol:
            print(f"Convergió después de {k+1} iteraciones.")
            return x

        # Calculamos beta using .flatten() to ensure 1D arrays for dot product
        beta = np.dot(r_new.flatten(), r_new.flatten()) / np.dot(r.flatten(), r.flatten())

        # Actualizamos la dirección
        p = r_new + beta * p

        r = r_new  # Actualizamos el residuo

    print("Alcanzado el número máximo de iteraciones.")
    return x
#solucion del sistema de ecuaciones para cada valor propio
for valor in valores_propios:
  #sistema de ecuaciones para cada valor propio
  A_hat = A - valor * np.eye(n) #matriz (A-\landa I)
  b = np.zeros((n,1)) #vector 0 de dimension nx1
  x0 = np.ones((n,1))#valor de inicio para el método gauss seidel en este caso la identidad
  x = gradiente_conjugado(A_hat,b,x0, 1e-4,100)#solución del sistema de ecuaciones (A-\landa I)x=0
  print(f"El autovector asociado a {valor} es {x}")

Evaluación de la matriz E:
La matriz [[1 1 2]
 [2 1 3]
 [1 1 1]]
Alcanzado el número máximo de iteraciones.
El autovector asociado a -0.6920214717683855 es [[-0.13844043]
 [-0.3744919 ]
 [ 0.30404775]]
Convergió después de 97 iteraciones.
El autovector asociado a -0.35689586788066696 es [[ 0.15540855]
 [-0.03851042]
 [-0.08616923]]
Convergió después de 3 iteraciones.
El autovector asociado a 4.0489173393871205 es [[0.97867741]
 [1.41425834]
 [0.78485966]]


In [13]:
import numpy as np

print("Evaluación de la matriz F:")
A = np.array([[2,1,2],[1,1,3],[1,1,1]])

print("La matriz", A)


B = 1 + max(np.abs(np.poly(A)/np.poly(A)[0])) #calculo de la cota de cauchy-lagrage para polinomios

def evaluar(pol, x): #definiion de la funciòn evaluar para polinomios
  pol = pol.copy()
  n = len(pol) - 1
  return sum([pol[i] * x ** (n-i) for i in range(n+1)])

#criterio de strums#
P = []#sucesión de polinomios
n = A.shape[0]#dimensiòn de la matriz por tanto numero de iteraciones de la sucesión
polinomio_original = np.poly(A)#determinante de (A-I\landa)
polinomio_polarizado = np.asarray([polinomio_original[i] * B ** (n - i) for i in range(n + 1)]) #cambio de variable#
P.append(polinomio_polarizado)#P_0 primer tèrmino de la sucesión
P.append(np.array([P[0][i] * (n-i) for i in range(0, n)]))#P_1 segundo término de la sucesión

for i in range(2, n + 1):
  P.append(-np.polynomial.polynomial.polydiv(P[i-2], P[i-1])[1])#descripción
def conteo_raices(intervalo):
  (a, b) = intervalo
  conteo_a = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion en la lista dada por el teorema de strums evaluada en los limites inferiores de cada subintervalo dada por la particiones
  for i in range(1, n+1):
    if evaluar(P[i-1], a) * evaluar(P[i],a) < 0:
      conteo_a += 1

  conteo_b = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion
  for i in range(1,n+1):
    if evaluar(P[i-1], b)*evaluar(P[i],b) < 0:
      conteo_b += 1

  return conteo_a - conteo_b #numero de raices en los intervalos encontrados en la partición#
max_raices = conteo_raices((-1, 1))
n1 = 0
while max_raices > 1:
  k = 2 ** n1
  intervalos = [(-1 + j / k, - 1 + (j + 1) / k) for j in range(2 * k)] #particion del intervalo [-1,1]#

  max_raices = 0
  for intervalo in intervalos:

    N = conteo_raices(intervalo) #conteo de raices en cada subintervalo definido por la partción

    if N > max_raices:
      max_raices = N #localización de la raices en las particiones del intervalo[-1,1]
  n1 += 1

 #aislamiento de raices#
verdaderos_intervalos = []
for intervalo in intervalos:
  if conteo_raices(intervalo) > 0:
    verdaderos_intervalos.append(intervalo)

def biseccion(intervalo, tol): #Función, extremos, y tolerancia
  (a, b) = intervalo
  p = a + ( b - a ) / 2 #Punto medio del intervalo
  if evaluar(P[0], p) == 0 or b-a < tol:
    return p
  elif evaluar(P[0], a) * evaluar(P[0], p) <0:
    return biseccion((a, p),tol)
  elif evaluar(P[0], p) * evaluar(P[0], b) <0:
    return biseccion((p, b),tol)  

#encontrar las raices del polinomio parametrizado usando el método de bisección#
raices = []
for intervalo in verdaderos_intervalos:
  raices.append(biseccion(intervalo, 10**(-10)))

valores_propios = [B * raiz for raiz in raices]#reparametrización de las raíces ubicadas en [-B,B]

#calculo de los vectores propios por gradiente conjugado#
import numpy as np

def gradiente_conjugado(A, b, x0=None, tol=1e-10, max_iter=1000):

    n = len(b)
    x = np.zeros_like(b) if x0 is None else x0.copy()  # Vector inicial (usualmente 0)
    r = b - np.dot(A, x)  # Resíduo inicial
    p = r.copy()  # Dirección de búsqueda inicial

    for k in range(max_iter):
        # Producto escalar de p con r using .flatten() to ensure 1D arrays for dot product
        # This ensures the dot product calculates a scalar as intended.
        alpha = np.dot(r.flatten(), r.flatten()) / np.dot(p.flatten(), np.dot(A, p).flatten())

        # Actualización de la solución
        x = x + alpha * p

        # Nuevo residuo
        r_new = r - alpha * np.dot(A, p)

        # Comprobar la convergencia
        if np.linalg.norm(r_new) < tol:
            print(f"Convergió después de {k+1} iteraciones.")
            return x

        # Calculamos beta using .flatten() to ensure 1D arrays for dot product
        beta = np.dot(r_new.flatten(), r_new.flatten()) / np.dot(r.flatten(), r.flatten())

        # Actualizamos la dirección
        p = r_new + beta * p

        r = r_new  # Actualizamos el residuo

    print("Alcanzado el número máximo de iteraciones.")
    return x
#solucion del sistema de ecuaciones para cada valor propio
for valor in valores_propios:
  #sistema de ecuaciones para cada valor propio
  A_hat = A - valor * np.eye(n) #matriz (A-\landa I)
  b = np.zeros((n,1)) #vector 0 de dimension nx1
  x0 = np.ones((n,1))#valor de inicio para el método gauss seidel en este caso la identidad
  x = gradiente_conjugado(A_hat,b,x0, 1e-4,100)#solución del sistema de ecuaciones (A-\landa I)x=0
  print(f"El autovector asociado a {valor} es {x}")

Evaluación de la matriz F:
La matriz [[2 1 2]
 [1 1 3]
 [1 1 1]]
Convergió después de 4 iteraciones.
El autovector asociado a -0.7615571819769678 es [[-0.02657073]
 [-0.31929765]
 [ 0.19635209]]
Convergió después de 9 iteraciones.
El autovector asociado a 0.6366717621858692 es [[-0.21364274]
 [ 0.19646238]
 [ 0.04739824]]
Convergió después de 12 iteraciones.
El autovector asociado a 4.124885419878407 es [[1.24020542]
 [1.12289804]
 [0.75623114]]


In [ ]:
import numpy as np

print("Evaluación de la matriz G:")
A = np.array([[1,1,1,2],[2,1,1,1],[3,2,1,2],[2,1,1,4]])

print("La matriz", A)


B = 1 + max(np.abs(np.poly(A)/np.poly(A)[0])) #calculo de la cota de cauchy-lagrage para polinomios

def evaluar(pol, x): #definiion de la funciòn evaluar para polinomios
  pol = pol.copy()
  n = len(pol) - 1
  return sum([pol[i] * x ** (n-i) for i in range(n+1)])

#criterio de strums#
P = []#sucesión de polinomios
n = A.shape[0]#dimensiòn de la matriz por tanto numero de iteraciones de la sucesión
polinomio_original = np.poly(A)#determinante de (A-I\landa)
polinomio_polarizado = np.asarray([polinomio_original[i] * B ** (n - i) for i in range(n + 1)]) #cambio de variable#
P.append(polinomio_polarizado)#P_0 primer tèrmino de la sucesión
P.append(np.array([P[0][i] * (n-i) for i in range(0, n)]))#P_1 segundo término de la sucesión

for i in range(2, n + 1):
  P.append(-np.polynomial.polynomial.polydiv(P[i-2], P[i-1])[1])#descripción
def conteo_raices(intervalo):
  (a, b) = intervalo
  conteo_a = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion en la lista dada por el teorema de strums evaluada en los limites inferiores de cada subintervalo dada por la particiones
  for i in range(1, n+1):
    if evaluar(P[i-1], a) * evaluar(P[i],a) < 0:
      conteo_a += 1

  conteo_b = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion
  for i in range(1,n+1):
    if evaluar(P[i-1], b)*evaluar(P[i],b) < 0:
      conteo_b += 1

  return conteo_a - conteo_b #numero de raices en los intervalos encontrados en la partición#
max_raices = conteo_raices((-1, 1))
n1 = 0
while max_raices > 1:
  k = 2 ** n1
  intervalos = [(-1 + j / k, - 1 + (j + 1) / k) for j in range(2 * k)] #particion del intervalo [-1,1]#

  max_raices = 0
  for intervalo in intervalos:

    N = conteo_raices(intervalo) #conteo de raices en cada subintervalo definido por la partción

    if N > max_raices:
      max_raices = N #localización de la raices en las particiones del intervalo[-1,1]
  n1 += 1

 #aislamiento de raices#
verdaderos_intervalos = []
for intervalo in intervalos:
  if conteo_raices(intervalo) > 0:
    verdaderos_intervalos.append(intervalo)

def biseccion(intervalo, tol): #Función, extremos, y tolerancia
  (a, b) = intervalo
  p = a + ( b - a ) / 2 #Punto medio del intervalo
  if evaluar(P[0], p) == 0 or b-a < tol:
    return p
  elif evaluar(P[0], a) * evaluar(P[0], p) <0:
    return biseccion((a, p),tol)
  elif evaluar(P[0], p) * evaluar(P[0], b) <0:
    return biseccion((p, b),tol)  

#encontrar las raices del polinomio parametrizado usando el método de bisección#
raices = []
for intervalo in verdaderos_intervalos:
  raices.append(biseccion(intervalo, 10**(-10)))

valores_propios = [B * raiz for raiz in raices]#reparametrización de las raíces ubicadas en [-B,B]

#calculo de los vectores propios por gradiente conjugado#
import numpy as np

def gradiente_conjugado(A, b, x0=None, tol=1e-10, max_iter=1000):

    n = len(b)
    x = np.zeros_like(b) if x0 is None else x0.copy()  # Vector inicial (usualmente 0)
    r = b - np.dot(A, x)  # Resíduo inicial
    p = r.copy()  # Dirección de búsqueda inicial

    for k in range(max_iter):
        # Producto escalar de p con r using .flatten() to ensure 1D arrays for dot product
        # This ensures the dot product calculates a scalar as intended.
        alpha = np.dot(r.flatten(), r.flatten()) / np.dot(p.flatten(), np.dot(A, p).flatten())

        # Actualización de la solución
        x = x + alpha * p

        # Nuevo residuo
        r_new = r - alpha * np.dot(A, p)

        # Comprobar la convergencia
        if np.linalg.norm(r_new) < tol:
            print(f"Convergió después de {k+1} iteraciones.")
            return x

        # Calculamos beta using .flatten() to ensure 1D arrays for dot product
        beta = np.dot(r_new.flatten(), r_new.flatten()) / np.dot(r.flatten(), r.flatten())

        # Actualizamos la dirección
        p = r_new + beta * p

        r = r_new  # Actualizamos el residuo

    print("Alcanzado el número máximo de iteraciones.")
    return x
#solucion del sistema de ecuaciones para cada valor propio
for valor in valores_propios:
  #sistema de ecuaciones para cada valor propio
  A_hat = A - valor * np.eye(n) #matriz (A-\landa I)
  b = np.zeros((n,1)) #vector 0 de dimension nx1
  x0 = np.ones((n,1))#valor de inicio para el método gauss seidel en este caso la identidad
  x = gradiente_conjugado(A_hat,b,x0, 1e-4,100)#solución del sistema de ecuaciones (A-\landa I)x=0
  print(f"El autovector asociado a {valor} es {x}")

Evaluación de la matriz C:
La matriz [[1 1 1 2]
 [2 1 1 1]
 [3 2 1 2]
 [2 1 1 4]]
Alcanzado el número máximo de iteraciones.
El autovector asociado a -0.7356415383401327 es [[ 0.2811418 ]
 [-0.13023589]
 [-0.26190859]
 [-0.04755902]]
Alcanzado el número máximo de iteraciones.
El autovector asociado a -0.40745626989519224 es [[-4.52244944]
 [-0.77577676]
 [ 0.93285599]
 [ 3.97584893]]
Convergió después de 14 iteraciones.
El autovector asociado a 1.508563345123548 es [[ 0.05073573]
 [ 0.25608655]
 [ 0.28773602]
 [-0.2590061 ]]
Convergió después de 16 iteraciones.
El autovector asociado a 6.634534463810269 es [[0.76679214]
 [0.69196406]
 [1.10223807]
 [1.26315531]]


In [ ]:
import numpy as np

print("Evaluación de la matriz H:")
A = np.array([[1,2,1,2],[2,1,1,1],[3,2,1,2],[2,1,1,4]])

print("La matriz", A)


B = 1 + max(np.abs(np.poly(A)/np.poly(A)[0])) #calculo de la cota de cauchy-lagrage para polinomios

def evaluar(pol, x): #definiion de la funciòn evaluar para polinomios
  pol = pol.copy()
  n = len(pol) - 1
  return sum([pol[i] * x ** (n-i) for i in range(n+1)])

#criterio de strums#
P = []#sucesión de polinomios
n = A.shape[0]#dimensiòn de la matriz por tanto numero de iteraciones de la sucesión
polinomio_original = np.poly(A)#determinante de (A-I\landa)
polinomio_polarizado = np.asarray([polinomio_original[i] * B ** (n - i) for i in range(n + 1)]) #cambio de variable#
P.append(polinomio_polarizado)#P_0 primer tèrmino de la sucesión
P.append(np.array([P[0][i] * (n-i) for i in range(0, n)]))#P_1 segundo término de la sucesión

for i in range(2, n + 1):
  P.append(-np.polynomial.polynomial.polydiv(P[i-2], P[i-1])[1])#descripción
def conteo_raices(intervalo):
  (a, b) = intervalo
  conteo_a = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion en la lista dada por el teorema de strums evaluada en los limites inferiores de cada subintervalo dada por la particiones
  for i in range(1, n+1):
    if evaluar(P[i-1], a) * evaluar(P[i],a) < 0:
      conteo_a += 1

  conteo_b = 0 #conteo de los cambios de signos en cada uno de los intervalos dados por la particion
  for i in range(1,n+1):
    if evaluar(P[i-1], b)*evaluar(P[i],b) < 0:
      conteo_b += 1

  return conteo_a - conteo_b #numero de raices en los intervalos encontrados en la partición#
max_raices = conteo_raices((-1, 1))
n1 = 0
while max_raices > 1:
  k = 2 ** n1
  intervalos = [(-1 + j / k, - 1 + (j + 1) / k) for j in range(2 * k)] #particion del intervalo [-1,1]#

  max_raices = 0
  for intervalo in intervalos:

    N = conteo_raices(intervalo) #conteo de raices en cada subintervalo definido por la partción

    if N > max_raices:
      max_raices = N #localización de la raices en las particiones del intervalo[-1,1]
  n1 += 1

 #aislamiento de raices#
verdaderos_intervalos = []
for intervalo in intervalos:
  if conteo_raices(intervalo) > 0:
    verdaderos_intervalos.append(intervalo)

def biseccion(intervalo, tol): #Función, extremos, y tolerancia
  (a, b) = intervalo
  p = a + ( b - a ) / 2 #Punto medio del intervalo
  if evaluar(P[0], p) == 0 or b-a < tol:
    return p
  elif evaluar(P[0], a) * evaluar(P[0], p) <0:
    return biseccion((a, p),tol)
  elif evaluar(P[0], p) * evaluar(P[0], b) <0:
    return biseccion((p, b),tol)  

#encontrar las raices del polinomio parametrizado usando el método de bisección#
raices = []
for intervalo in verdaderos_intervalos:
  raices.append(biseccion(intervalo, 10**(-10)))

valores_propios = [B * raiz for raiz in raices]#reparametrización de las raíces ubicadas en [-B,B]

#calculo de los vectores propios por gradiente conjugado#
import numpy as np

def gradiente_conjugado(A, b, x0=None, tol=1e-10, max_iter=1000):

    n = len(b)
    x = np.zeros_like(b) if x0 is None else x0.copy()  # Vector inicial (usualmente 0)
    r = b - np.dot(A, x)  # Resíduo inicial
    p = r.copy()  # Dirección de búsqueda inicial

    for k in range(max_iter):
        # Producto escalar de p con r using .flatten() to ensure 1D arrays for dot product
        # This ensures the dot product calculates a scalar as intended.
        alpha = np.dot(r.flatten(), r.flatten()) / np.dot(p.flatten(), np.dot(A, p).flatten())

        # Actualización de la solución
        x = x + alpha * p

        # Nuevo residuo
        r_new = r - alpha * np.dot(A, p)

        # Comprobar la convergencia
        if np.linalg.norm(r_new) < tol:
            print(f"Convergió después de {k+1} iteraciones.")
            return x

        # Calculamos beta using .flatten() to ensure 1D arrays for dot product
        beta = np.dot(r_new.flatten(), r_new.flatten()) / np.dot(r.flatten(), r.flatten())

        # Actualizamos la dirección
        p = r_new + beta * p

        r = r_new  # Actualizamos el residuo

    print("Alcanzado el número máximo de iteraciones.")
    return x
#solucion del sistema de ecuaciones para cada valor propio
for valor in valores_propios:
  #sistema de ecuaciones para cada valor propio
  A_hat = A - valor * np.eye(n) #matriz (A-\landa I)
  b = np.zeros((n,1)) #vector 0 de dimension nx1
  x0 = np.ones((n,1))#valor de inicio para el método gauss seidel en este caso la identidad
  x = gradiente_conjugado(A_hat,b,x0, 1e-4,100)#solución del sistema de ecuaciones (A-\landa I)x=0
  print(f"El autovector asociado a {valor} es {x}")

Evaluación de la matriz C:
La matriz [[1 2 1 2]
 [2 1 1 1]
 [3 2 1 2]
 [2 1 1 4]]
Alcanzado el número máximo de iteraciones.
El autovector asociado a -1.0879349235619895 es [[-1.27614586]
 [-1.12265071]
 [ 3.25656738]
 [ 0.3039847 ]]
Alcanzado el número máximo de iteraciones.
El autovector asociado a -0.4674432346655526 es [[-0.64370116]
 [ 0.32797282]
 [ 0.03379057]
 [-0.19546314]]
Alcanzado el número máximo de iteraciones.
El autovector asociado a 1.7281159081903767 es [[ 0.23814414]
 [ 0.27483454]
 [ 0.10148841]
 [-0.15863156]]
Convergió después de 10 iteraciones.
El autovector asociado a 6.827262250153587 es [[0.85299241]
 [0.69467512]
 [1.1028545 ]
 [1.23917856]]
