## Experimentos
Copiamos los códigos de las funciones usadas en QR, e importamos las matrices propuestas para usar como ejemplos

In [3]:
import numpy as np
def QR_factor(A): #Gram-Schmidt modificado
    """
    Entrada: A matriz de numpy invertible n x n
    Proceso de ortogonalización de Gram-Smith modificado en los vectores columna de A
    Salida: Q y R con Q ortogonal y R triangular superior con diagonal positiva tales que A = Q R
    """
    n = A.shape[0]
    v = np.zeros((n,n)) 
    Q = np.zeros((n,n))
    R = np.zeros((n,n))
   
    for i in range(n):
        v[:,i] = A[:,i] #Inicializamos A
    #print(v)
    for i in range(n):
        R[i,i] = np.linalg.norm( v[:,i]) #Como esto es el coeficiente de q_i en la i-ésima fila, es la i,i-ésima componente de R
        Q[:,i] = (1/R[i,i]) * v[:,i] #Normalizamos v_i
        for k in range(i+1,n):
            R[i,k] = Q[:,i] @ v[:,k] #Esto será el coeficiente de q_i en la k-ésima fila, por tanto es la i,k-ésima componente de R
            v[:,k] = v[:,k] - R[i,k] * Q[:,i] #Actualizamos v_k restándole la proyección <q_i,v_k>q_i
    return Q,R

In [41]:
def bottom_half(A):
    """
    Almacena las componentes debajo de la diagonal superior de A
    """
    n = A.shape[0]
    L=[]
    for i in range(n):
        T = list(A[i,:])
        for k in range(i):   
            L.append(T[k])
    return L

In [119]:
def QR_algor(A,max_iteraciones=10000,tol=10e-8):
    """
    Entrada: A matriz de numpy que debería ser simple e invertible, con autovalores distintos en módulo
             max_iteraciones: tope de recursion. si se alcanza se retorna error
             tol: tolerancia, que tan cerca de ser triangular superior es la matriz A^(n) en el paso n
    Salida: B matriz (casi) triangular superior similar a A, con sus autovalores ordenados por su módulo en la diagonal, lista con los autovalores, iteraciones necesarias
    """
    iteracion = 0
    n=A.shape[0]
    while iteracion < max_iteraciones:
        iteracion += 1
        Q,R = QR_factor(A) #Calculamos la descomposición A_k = Q'_k R'_k
        A = R @ Q  #Y hacemos A_(k+1) = R'_k Q'_k. Sabemos que sto es equivalente a Q_k^T A Q_k obtenidas por iteración simultánea, y converge a una matriz triangular superior
        L = [abs(l) for l in bottom_half(A)] #Para chequear si estamos suficientemente cerca, tomamos los valores absolutos de la mitad triangular inferior de A...
        if max(L) < tol: #Y aceptamos si todos son menores que la tolerancia
            Autovalores = [A[i][i] for i in range(n)] #Almacenamos los autovalores aqui
            return A,Autovalores,iteracion
    print(A)
    print(Q)
    print(Q.transpose() @ Q)
    print ("Iteraciones máximas alcanzadas")
    print ("Matriz actual:")
    return A,[],iteracion #Error si no converge suficientemente rápido. Igual es de interés ver a que resultado se llegó

In [142]:
A = np.array([[2, 1], 
             [3, 4]])

B = np.array([[3, 2],
             [3, 4]])  

C = np.array([[2, 3],
             [1, 4]])

D = np.array([[1, 1, 2],
             [2, 1, 1], 
             [1, 1, 3]])

E = np.array([[1, 1, 2],
             [2, 1, 3],
             [1, 1, 1]])

F = np.array([[2, 1, 2],
             [1, 1, 3],
             [1, 1, 1]])

G = np.array([[1, 1, 1, 2], 
             [2, 1, 1, 1],
             [3, 2, 1, 2],
             [2, 1, 1, 4]])

H = np.array([[1, 2, 1, 2],
             [2, 1, 1, 1], 
             [3, 2, 1, 2],
             [2, 1, 1, 4]])
matrices_ejemplo = [A,B,C,D,E,F,G,H]
nombres = ['A','B','C','D','E','F','G','H']

Corremos el algoritmo en las matrices de ejemplo dadas

In [141]:
for j in range(len(matrices_ejemplo)):
    AA,Autovalores,i = QR_algor(matrices_ejemplo[j],tol=1e-5)
    with np.printoptions(precision=6, suppress=True, formatter={'float': '{:0.6f}'.format}, linewidth=100):
        print(f"Matriz (casi) diagonal similar a { nombres[j] }:")
        print(AA)
        print(f"Autovalores de {nombres[j]}:{Autovalores}, en {i} pasos")

Matriz (casi) diagonal similar a A:
[[5.000001 -1.999998]
 [0.000002 0.999999]]
Autovalores de A:[5.000001228798867, 0.9999987712011326], en 9 pasos
Matriz (casi) diagonal similar a B:
[[6.000001 -0.999997]
 [0.000003 0.999999]]
Autovalores de B:[6.0000006869679465, 0.9999993130320568], en 8 pasos
Matriz (casi) diagonal similar a C:
[[4.999998 2.000004]
 [0.000004 1.000002]]
Autovalores de C:[4.999997951996856, 1.0000020480031455], en 9 pasos
Matriz (casi) diagonal similar a D:
[[4.507019 0.749926 0.196802]
 [0.000000 0.778117 1.182749]
 [0.000000 0.000006 -0.285135]]
Autovalores de D:[4.5070186438981645, 0.7781167256742583, -0.285135369572424], en 13 pasos
Matriz (casi) diagonal similar a E:
[[4.048917 2.394759 0.498778]
 [0.000000 -0.692024 -0.127854]
 [0.000000 0.000006 -0.356894]]
Autovalores de E:[4.048917339522198, -0.692023659831876, -0.35689367969032243], en 17 pasos
Matriz (casi) diagonal similar a F:
[[4.124885 1.839028 1.035010]
 [-0.000000 -0.761562 -0.739402]
 [0.000000 0.